{% set version = "0.4" %}
{% set ot_version = "1.11rc1" %}

package:
  name: otmorris
  version: {{ version }}

source:
  fn: otmorris-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otmorris/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 73f10f6d39cb940fea075578b9070fd30420a79492a26735e7597205c8db589f  # [not win]

  fn: otmorris-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otmorris-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: b3bd8147143eab2014e394889009625da5c3586427fa8a5f429c5a9ba2ba4aed  # [win64 and py27]

  fn: otmorris-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otmorris-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 75c91cf61aed493995116687f1cc1ce0e582eee8d81cbada48c45afe30f9fff4  # [win64 and py35]

  fn: otmorris-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otmorris-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 0f85a994d12c9a0be0e0197270b1c92d5cee936322ed6ec4aa0c527560f8ce63  # [win64 and py36]

build:
  number: 1

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
  run:
    - python
    - openturns

test:
  imports:
    - otmorris

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: Morris screening module

extra:
  recipe-maintainers:
    - jschueller
