travis:
  secure:
    BINSTAR_TOKEN: W462exgJLgZx8057vlCFX6nkQT5btOzE2S6wqOOTjelfDTdTGlgTRcPmq/CMtrtikOpYezMflzRzgd4K/bvUVynZMoM6ezT6YSPxN8fWLH8av1kGCWfRZqdlGvpKKHRT01ePUZXrpqJfn4d6Sp7lqTup/C/iLiF+2pZqNTJuL01RVep4PpyUG2ycxPauCf5jSYwhqmVS5Bi0bp+rQAABE/W7F4TbEv087Hc6CCD0DgSlLkgRnTMKpxckdsLWywYa3IRKs2ex3HYBl8u2x+U7w9sUPEe0dr87+c98Mq3Mvekqoi603AUZ/wDkWQXlUi5nAzVHd7oFxycH15SXqyrw8uOQ2DgezaLAc8oHov+fc78K2VtAWWo1H9LOwWa+0MtdQoB+TsBr5QWtHyIabwHsp2R9CDm2K8Wr9Zm9GV9SnnWaNdxN6/63Z6OVxZ71H41s+KSOCJF5svWgIjACOwVnypSues+cuSK325cflfDLbasU3rPzUJM2VR5o8IzovbMmjf0ZEU3oBYj3IYafIOGGcQsuywPQoamFHak0+9bGWozZsS7DVznBfbCwu+EC5+IQb10zOGXsRZlWy7rFOV/jnO/GQl3whDUSJ5sWX9Ub6iCzKczG3bse/6rM6Ye2qNbQXet0KeQd6O2zmZ8Zqe2tURP5KzPYcB+az5hl78tWvfI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
