travis:
  secure:
    BINSTAR_TOKEN: Ns+GyHOuAZebMvHdKB/JeFZuXMH3ZNH5y4LDVZx7o2u/6ENQlGNYLQB1zZjCPYCh8QWiEeHmEZFxu0QOssJvyfPR1SBGt6b+n1gduPwX3G1QSgSlTIGtlzChO6WtX2oYneKONVwFa6Le8MtImufpW1jHGlNVzbiD2keqfbfroHSmjVtiQYOKGnB1W5W2zmYog8dsy/a12bwh9Hy8zfxEV79t/NFCNYVy6BFpqrNbOdIP1PF6Iim4MOv6jbVrSc/AUZPyjn55iOTco9fRzjzZiXVc22p+TmGbgKUMhaCyIB+l+Wry2M2guD4qcXmEZmJ1SNMmWT+NmuMFHdCC/hpipvckMdfwxFioZdMvRB9jwBAzbyQHDfh0X8ntBZu8S6hy7OH3ox3PzyuyFKdgBMvEkZR1Yh69NhBU18kShXcjNH/RQgh/LrJ1EbaKFIuj1Ou3hvkY9andsWCs/ZjVPuYsqNr8F8ToVY3Fw1i8c7Uw14gVRoiSmSeW1ir18Tn+tB9K9Trtlwuyoj5LIj2qfJhnkBMx1ee00no5Y9yc1hbYscBdKlr2JIK2ZAR2BP8a1FW9eL9NWpXeCu/uAkLsOGZ+BNunCuhZZ9JPpKRpbfm9aMFwnlw1YT7d4JOfymB9dQ8cih/xuIJ2PiYbZyXcHpua67QhSE5+iS2URM9q4tM1sLc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
