travis:
  secure:
    BINSTAR_TOKEN: CH6KGustXegHJnJasatHPtYzp6tO7VURfvhXw9ZisGTben9upgStOvuzEIOn0ohXt7gkBM91Y2Du2IoIZ0YskQZsGXfMTfZInVUKIE4TtGHTIzE6IRzzuVoJlsWJjsVSvsyQ2H8bKnD3mEoBig7Xe9Bm9e1mM+cHULR47F+swx2bMbJBI6wIQftuu2D53Ra3WS9O+aisvSr1ljrHb4XO5Jvp5eMkbmb+TT31mUzMA3Kre547eHTTkWi2hQvUQlC96KEvf5psvenRuzAEOiCZSj1MtENDFiJeSZPBOPxSD23w2Mww/RX+nAYSbF5wS8lAh8YCcsJVyMAQWBFNuQm7N6zlHSvUNju0QBp8etfQZaGPjXr3x18CCtYfXu9rzLUM/Tc4bbvpT9DgzDmoi51BBEbW1Uq5vc6mrab53rArBZnA0qfZU4rEK/yOn420YPbkskKXlh55hTMTdIdcwQK8gG8nkSOCYuu6coLHNTtGBH1JTJocNO5LqoTIEihBN1xC0veOjsNGh/4rs9h1SAFfwxqJxLZ48BvQk9mQEnrfKzTmDSI+8KiTXC+nj6tjTduxLXvhEqJtGf4yFuDz3T7wN06BHOW0ATqT43CQ26G8dX0MX2/5pOkUwUUpIi+kRfoZhIrPsM3nTUNbVFUtH12AELr9eKnMtv9C8dI4F6cP6+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
